# Generated by Django 5.1.4 on 2025-08-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_deals"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
